In [82]:

import os

print("Current Directory:")
print(os.getcwd())

print("\nFiles/Folders:")
print(os.listdir())

Current Directory:
d:\IPL_PROJECT\notebook

Files/Folders:
['data_understanding.ipynb', 'deliveries.csv', 'eda.ipynb', 'ipl_new.csv', 'matches.csv']

In [83]:
import pandas as pd

matches = pd.read_csv("matches.csv")
deliveries = pd.read_csv("deliveries.csv")

In [84]:
matches.head()

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
0,1,"March 28, 2026","M. Chinnaswamy Stadium, Bangalore",RCB,SRH,League,RCB,Bowl,201.0,9.0,...,RCB,NaN,6.0,26.0,Jacob Duffy,Ishan Kishan,80.0,Jacob Duffy,3--22,No
1,2,"March 29, 2026","Wankhede Stadium, Mumbai",MI,KKR,League,MI,Bowl,220.0,4.0,...,MI,NaN,6.0,5.0,Shardul Thakur,Ryan Rickelton,81.0,Shardul Thakur,3--39,No
2,3,"March 30, 2026","Barsapara Stadium, Guwahati",RR,CSK,League,RR,Bowl,127.0,10.0,...,RR,NaN,8.0,47.0,Nandre Burger,Vaibhav Sooryavanshi,52.0,Jofra Archer,2--19,No
3,4,"March 31, 2026","New PCA Cricket Stadium, Mullanpur",PBKS,GT,League,PBKS,Bowl,162.0,6.0,...,PBKS,NaN,3.0,5.0,Cooper Connolly,Cooper Connolly,72.0,Prasidh Krishna,3--29,No
4,5,"April 01, 2026","Ekana Cricket Stadium, Lucknow",LSG,DC,League,DC,Bowl,141.0,10.0,...,DC,NaN,6.0,17.0,Sameer Rizvi,Sameer Rizvi,70.0,Lungi Ngidi,3--27,No

In [85]:
deliveries.head()

,match_no,date,stage,venue,batting_team,bowling_team,innings,over,striker,bowler,runs_of_bat,extras,wide,legbyes,byes,noballs,wicket_type,player_dismissed,fielder
0,1,"Mar 28, 2026",League stage,"M.Chinnaswamy Stadium, Bengaluru",SRH,RCB,1,0.1,Travis Head,Jacob Duffy,0,0,0,0,0,0,NaN,NaN,NaN
1,1,"Mar 28, 2026",League stage,"M.Chinnaswamy Stadium, Bengaluru",SRH,RCB,1,0.2,Travis Head,Jacob Duffy,1,0,0,0,0,0,NaN,NaN,NaN
2,1,"Mar 28, 2026",League stage,"M.Chinnaswamy Stadium, Bengaluru",SRH,RCB,1,0.3,Abhishek Sharma,Jacob Duffy,0,0,0,0,0,0,NaN,NaN,NaN
3,1,"Mar 28, 2026",League stage,"M.Chinnaswamy Stadium, Bengaluru",SRH,RCB,1,0.4,Abhishek Sharma,Jacob Duffy,6,0,0,0,0,0,NaN,NaN,NaN
4,1,"Mar 28, 2026",League stage,"M.Chinnaswamy Stadium, Bengaluru",SRH,RCB,1,0.5,Abhishek Sharma,Jacob Duffy,0,0,0,0,0,0,NaN,NaN,NaN

In [86]:
matches.tail()

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,...,match_winner,wb_runs,wb_wickets,balls_left,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure,super_over_match
34,35,"April 25, 2026","Arun Jaitley Stadium, Delhi",DC,PBKS,League,DC,Bat,264.0,2.0,...,PBKS,NaN,6.0,7.0,KL Rahul,KL Rahul,152.0,Kuldeep Yadav,2--46,No
35,36,"April 25, 2026","Sawai Mansingh Stadium, Jaipur",RR,SRH,League,SRH,Bowl,228.0,6.0,...,SRH,NaN,5.0,9.0,Ishan Kishan,Vaibhav Sooryavanshi,103.0,Jofra Archer,2--34,No
36,37,"April 26, 2026","Narendra Modi Stadium, Ahmedabad",GT,CSK,League,GT,Bowl,158.0,7.0,...,GT,NaN,8.0,20.0,Kagiso Rabada,Sai Sudarshan,87.0,Kagiso Rabada,3--25,No
37,38,"April 26, 2026","Ekana Cricket Stadium, Lucknow",LSG,KKR,League,LSG,Bowl,155.0,7.0,...,KKR,NaN,NaN,5.0,Rinku Singh,Rinku Singh,83.0,Mohsin Khan,5--23,Yes
38,39,"April 27, 2026","Arun Jaitley Stadium, Delhi",DC,RCB,League,RCB,Bowl,75.0,10.0,...,RCB,NaN,9.0,81.0,Josh Hazlewood,Devdutt Padikkal,34.0,Josh Hazlewood,4--12,No

In [87]:
deliveries.tail()

,match_no,date,stage,venue,batting_team,bowling_team,innings,over,striker,bowler,runs_of_bat,extras,wide,legbyes,byes,noballs,wicket_type,player_dismissed,fielder
17472,74,"May 31, 2026",Final,"Narendra Modi Stadium, Ahmedabad",RCB,GT,2,17.2,Virat Kohli,Arshad Khan,1,0,0,0,0,0,NaN,NaN,NaN
17473,74,"May 31, 2026",Final,"Narendra Modi Stadium, Ahmedabad",RCB,GT,2,17.3,Jitesh Sharma,Arshad Khan,0,0,0,0,0,0,NaN,NaN,NaN
17474,74,"May 31, 2026",Final,"Narendra Modi Stadium, Ahmedabad",RCB,GT,2,17.4,Jitesh Sharma,Arshad Khan,1,0,0,0,0,0,NaN,NaN,NaN
17475,74,"May 31, 2026",Final,"Narendra Modi Stadium, Ahmedabad",RCB,GT,2,17.5,Virat Kohli,Arshad Khan,4,0,0,0,0,0,NaN,NaN,NaN
17476,74,"May 31, 2026",Final,"Narendra Modi Stadium, Ahmedabad",RCB,GT,2,17.6,Virat Kohli,Arshad Khan,6,0,0,0,0,0,NaN,NaN,NaN

In [88]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   match_id             39 non-null     int64
 1   date                 39 non-null     str
 2   venue                39 non-null     str
 3   team1                39 non-null     str
 4   team2                39 non-null     str
 5   stage                39 non-null     str
 6   toss_winner          39 non-null     str
 7   toss_decision        39 non-null     str
 8   first_ings_score     38 non-null     float64
 9   first_ings_wkts      38 non-null     float64
 10  second_ings_score    38 non-null     float64
 11  second_ings_wkts     38 non-null     float64
 12  match_result         39 non-null     str
 13  match_winner         38 non-null     str
 14  wb_runs              15 non-null     float64
 15  wb_wickets           22 non-null     float64
 16  balls_left           38 non-null     float64
 17  player_of_the_match  38 non-null     str
 18  top_scorer           38 non-null     str
 19  highscore            38 non-null     float64
 20  best_bowling         38 non-null     str
 21  best_bowling_figure  38 non-null     str
 22  super_over_match     39 non-null     str
dtypes: float64(8), int64(1), str(14)
memory usage: 11.7 KB

In [89]:
deliveries.info()

<class 'pandas.DataFrame'>
RangeIndex: 17477 entries, 0 to 17476
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   match_no          17477 non-null  int64
 1   date              17477 non-null  str
 2   stage             17477 non-null  str
 3   venue             17477 non-null  str
 4   batting_team      17477 non-null  str
 5   bowling_team      17477 non-null  str
 6   innings           17477 non-null  int64
 7   over              17477 non-null  float64
 8   striker           17477 non-null  str
 9   bowler            17477 non-null  str
 10  runs_of_bat       17477 non-null  int64
 11  extras            17477 non-null  int64
 12  wide              17477 non-null  int64
 13  legbyes           17477 non-null  int64
 14  byes              17477 non-null  int64
 15  noballs           17477 non-null  int64
 16  wicket_type       879 non-null    str
 17  player_dismissed  875 non-null    str
 18  fielder           686 non-null    str
dtypes: float64(1), int64(8), str(10)
memory usage: 4.2 MB

In [90]:

matches.describe()

,match_id,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,wb_runs,wb_wickets,balls_left,highscore
count,39.000000,38.000000,38.000000,38.000000,38.000000,15.000000,22.000000,38.000000,38.000000
mean,20.000000,190.526316,6.289474,175.500000,6.052632,41.666667,5.772727,10.684211,79.447368
std,11.401754,39.394565,2.470451,39.747684,2.670635,30.658643,1.477830,15.773918,24.521031
min,1.000000,75.000000,2.000000,77.000000,1.000000,1.000000,3.000000,0.000000,34.000000
25%,10.500000,159.750000,4.250000,159.250000,4.000000,20.500000,5.000000,0.250000,60.750000
50%,20.000000,197.000000,6.000000,180.000000,5.000000,40.000000,6.000000,6.000000,77.500000
75%,29.500000,215.000000,8.000000,203.750000,8.000000,55.500000,6.000000,12.000000,91.750000
max,39.000000,264.000000,10.000000,265.000000,10.000000,103.000000,9.000000,81.000000,152.000000

In [91]:
print("total matches:",matches.shape[0])

total matches: 39

In [92]:
teams = pd.concat([matches['team1'],
                   matches['team2']]).unique()
print("Total teams:",len(teams))
print(teams)

Total teams: 10
<ArrowStringArray>
['RCB', 'MI', 'RR', 'PBKS', 'LSG', 'KKR', 'CSK', 'DC', 'GT', 'SRH']
Length: 10, dtype: str

In [93]:
players = deliveries['striker'].unique()
print("total players:",len(players))

total players: 177

In [94]:
print(players[:20])

<ArrowStringArray>
[     'Travis Head',  'Abhishek Sharma',     'Ishan Kishan',
     'Nitish Reddy', 'Heinrich Klaasen',      'Salil Arora',
     'Aniket Verma',      'Harsh Dubey',    'Harshal Patel',
      'David Payne',   'Jaydev Unadkat',        'Phil Salt',
 'Devdutt Padikkal',      'Virat Kohli',    'Rajat Patidar',
    'Jitesh Sharma',        'Tim David',   'Ajinkya Rahane',
       'Finn Allen',    'Cameron Green']
Length: 20, dtype: str

In [95]:
matches.isnull().sum()

match_id                0
date                    0
venue                   0
team1                   0
team2                   0
stage                   0
toss_winner             0
toss_decision           0
first_ings_score        1
first_ings_wkts         1
second_ings_score       1
second_ings_wkts        1
match_result            0
match_winner            1
wb_runs                24
wb_wickets             17
balls_left              1
player_of_the_match     1
top_scorer              1
highscore               1
best_bowling            1
best_bowling_figure     1
super_over_match        0
dtype: int64

In [96]:
deliveries.isnull().sum()

match_no                0
date                    0
stage                   0
venue                   0
batting_team            0
bowling_team            0
innings                 0
over                    0
striker                 0
bowler                  0
runs_of_bat             0
extras                  0
wide                    0
legbyes                 0
byes                    0
noballs                 0
wicket_type         16598
player_dismissed    16602
fielder             16791
dtype: int64

In [97]:
print("Duplicate Rows in Matches:",
      matches.duplicated().sum())

Duplicate Rows in Matches: 0

In [98]:
print("Duplicate Rows in Deliveries:",
      deliveries.duplicated().sum())

Duplicate Rows in Deliveries: 0

In [99]:
print("="*50)

print("IPL DATASET SUMMARY")

print("="*50)

print("Total Matches:",
      matches.shape[0])

print("Total Teams:",
      len(pd.concat([
          matches['team1'],
          matches['team2']
      ]).unique()))

print("Total Players:",
      deliveries['striker'].nunique())

print("\nMissing Values in Matches:")
print(matches.isnull().sum())

print("\nMissing Values in Deliveries:")
print(deliveries.isnull().sum())

print("\nDuplicate Rows in Matches:",
      matches.duplicated().sum())

print("Duplicate Rows in Deliveries:",
      deliveries.duplicated().sum())

==================================================
IPL DATASET SUMMARY
==================================================
Total Matches: 39
Total Teams: 10
Total Players: 177

Missing Values in Matches:
match_id                0
date                    0
venue                   0
team1                   0
team2                   0
stage                   0
toss_winner             0
toss_decision           0
first_ings_score        1
first_ings_wkts         1
second_ings_score       1
second_ings_wkts        1
match_result            0
match_winner            1
wb_runs                24
wb_wickets             17
balls_left              1
player_of_the_match     1
top_scorer              1
highscore               1
best_bowling            1
best_bowling_figure     1
super_over_match        0
dtype: int64

Missing Values in Deliveries:
match_no                0
date                    0
stage                   0
venue                   0
batting_team            0
bowling_team            0
innings                 0
over                    0
striker                 0
bowler                  0
runs_of_bat             0
extras                  0
wide                    0
legbyes                 0
byes                    0
noballs                 0
wicket_type         16598
player_dismissed    16602
fielder             16791
dtype: int64

Duplicate Rows in Matches: 0
Duplicate Rows in Deliveries: 0

In [100]:
matches.dropna

<bound method DataFrame.dropna of     match_id            date                                          venue  \
0          1  March 28, 2026              M. Chinnaswamy Stadium, Bangalore
1          2  March 29, 2026                       Wankhede Stadium, Mumbai
2          3  March 30, 2026                    Barsapara Stadium, Guwahati
3          4  March 31, 2026             New PCA Cricket Stadium, Mullanpur
4          5  April 01, 2026                 Ekana Cricket Stadium, Lucknow
5          6  April 02, 2026                          Eden Gardens, Kolkata
6          7  April 03, 2026                MA Chidambaram Stadium, Chennai
7          8  April 04, 2026                    Arun Jaitley Stadium, Delhi
8          9  April 04, 2026               Narendra Modi Stadium, Ahmedabad
9         10  April 05, 2026  Rajiv Gandhi International Stadium, Hyderabad
10        11  April 05, 2026              M. Chinnaswamy Stadium, Bangalore
11        12  April 06, 2026                          Eden Gardens, Kolkata
12        13  April 07, 2026                    Barsapara Stadium, Guwahati
13        14  April 08, 2026                    Arun Jaitley Stadium, Delhi
14        15  April 09, 2026                          Eden Gardens, Kolkata
15        16  April 10, 2026                    Barsapara Stadium, Guwahati
16        17  April 11, 2026             New PCA Cricket Stadium, Mullanpur
17        18  April 11, 2026                MA Chidambaram Stadium, Chennai
18        19  April 12, 2026                 Ekana Cricket Stadium, Lucknow
19        20  April 12, 2026                       Wankhede Stadium, Mumbai
20        21  April 13, 2026  Rajiv Gandhi International Stadium, Hyderabad
21        22  April 14, 2026                MA Chidambaram Stadium, Chennai
22        23  April 15, 2026              M. Chinnaswamy Stadium, Bangalore
23        24  April 16, 2026                       Wankhede Stadium, Mumbai
24        25  April 17, 2026               Narendra Modi Stadium, Ahmedabad
25        26  April 18, 2026              M. Chinnaswamy Stadium, Bangalore
26        27  April 18, 2026  Rajiv Gandhi International Stadium, Hyderabad
27        28  April 19, 2026                          Eden Gardens, Kolkata
28        29  April 19, 2026             New PCA Cricket Stadium, Mullanpur
29        30  April 20, 2026               Narendra Modi Stadium, Ahmedabad
30        31  April 21, 2026  Rajiv Gandhi International Stadium, Hyderabad
31        32  April 22, 2026                 Ekana Cricket Stadium, Lucknow
32        33  April 23, 2026                       Wankhede Stadium, Mumbai
33        34  April 24, 2026              M. Chinnaswamy Stadium, Bangalore
34        35  April 25, 2026                    Arun Jaitley Stadium, Delhi
35        36  April 25, 2026                 Sawai Mansingh Stadium, Jaipur
36        37  April 26, 2026               Narendra Modi Stadium, Ahmedabad
37        38  April 26, 2026                 Ekana Cricket Stadium, Lucknow
38        39  April 27, 2026                    Arun Jaitley Stadium, Delhi

   team1 team2   stage toss_winner toss_decision  first_ings_score  \
0    RCB   SRH  League         RCB          Bowl             201.0
1     MI   KKR  League          MI          Bowl             220.0
2     RR   CSK  League          RR          Bowl             127.0
3   PBKS    GT  League        PBKS          Bowl             162.0
4    LSG    DC  League          DC          Bowl             141.0
5    KKR   SRH  League         KKR          Bowl             226.0
6    CSK  PBKS  League        PBKS          Bowl             209.0
7     DC    MI  League          DC          Bowl             162.0
8     GT    RR  League          RR           Bat             210.0
9    SRH   LSG  League         LSG          Bowl             156.0
10   RCB   CSK  League         CSK          Bowl             250.0
11   KKR  PBKS  League         KKR           Bat               NaN
12    RR    MI  League          MI          Bowl             150.0
13    DC    GT  League          DC          Bowl             210.0
14   KKR   LSG  League         LSG          Bowl             181.0
15    RR   RCB  League          RR          Bowl             201.0
16  PBKS   SRH  League        PBKS          Bowl             219.0
17   CSK    DC  League          DC          Bowl             212.0
18   LSG    GT  League          GT          Bowl             164.0
19    MI   RCB  League          MI          Bowl             240.0
20   SRH    RR  League          RR          Bowl             216.0
21   CSK   KKR  League         KKR          Bowl             192.0
22   RCB   LSG  League         RCB          Bowl             146.0
23    MI  PBKS  League        PBKS          Bowl             195.0
24    GT   KKR  League         KKR           Bat             180.0
25   RCB    DC  League          DC          Bowl             175.0
26   SRH   CSK  League         CSK          Bowl             194.0
27   KKR    RR  League          RR           Bat             155.0
28  PBKS   LSG  League         LSG          Bowl             254.0
29    GT    MI  League          GT          Bowl             199.0
30   SRH    DC  League          DC          Bowl             242.0
31   LSG    RR  League         LSG          Bowl             159.0
32    MI   CSK  League          MI          Bowl             207.0
33   RCB    GT  League         RCB          Bowl             205.0
34    DC  PBKS  League          DC           Bat             264.0
35    RR   SRH  League         SRH          Bowl             228.0
36    GT   CSK  League          GT          Bowl             158.0
37   LSG   KKR  League         LSG          Bowl             155.0
38    DC   RCB  League         RCB          Bowl              75.0

    first_ings_wkts  ...  match_winner  wb_runs wb_wickets balls_left  \
0               9.0  ...           RCB      NaN        6.0       26.0
1               4.0  ...            MI      NaN        6.0        5.0
2              10.0  ...            RR      NaN        8.0       47.0
3               6.0  ...          PBKS      NaN        3.0        5.0
4              10.0  ...            DC      NaN        6.0       17.0
5               8.0  ...           SRH     65.0        NaN       24.0
6               5.0  ...          PBKS      NaN        5.0        8.0
7               6.0  ...            DC      NaN        6.0       11.0
8               6.0  ...            RR      6.0        NaN        0.0
9               9.0  ...           LSG      NaN        5.0        1.0
10              3.0  ...           RCB     43.0        NaN        2.0
11              NaN  ...           NaN      NaN        NaN        NaN
12              3.0  ...            RR     27.0        NaN        0.0
13              4.0  ...            GT      1.0        NaN        0.0
14              4.0  ...           LSG      NaN        3.0        0.0
15              8.0  ...            RR      NaN        6.0       12.0
16              6.0  ...          PBKS      NaN        6.0        7.0
17              2.0  ...           CSK     23.0        NaN        0.0
18              8.0  ...            GT      NaN        7.0        8.0
19              4.0  ...           RCB     18.0        NaN        0.0
20              6.0  ...           SRH     57.0        NaN        6.0
21              5.0  ...           CSK     32.0        NaN        0.0
22             10.0  ...           RCB      NaN        5.0       29.0
23              6.0  ...          PBKS      NaN        7.0       21.0
24             10.0  ...            GT      NaN        5.0        2.0
25              8.0  ...            DC      NaN        6.0        1.0
26              9.0  ...           SRH     10.0        NaN        0.0
27              9.0  ...           KKR      NaN        4.0        2.0
28              7.0  ...          PBKS     54.0        NaN        0.0
29              5.0  ...            MI     99.0        NaN       25.0
30              2.0  ...           SRH     47.0        NaN        0.0
31              6.0  ...           LSG     40.0        NaN       12.0
32              6.0  ...           CSK    103.0        NaN        6.0
33              3.0  ...           RCB      NaN        5.0        7.0
34              2.0  ...          PBKS      NaN        6.0        7.0
35              6.0  ...           SRH      NaN        5.0        9.0
36              7.0  ...            GT      NaN        8.0       20.0
37              7.0  ...           KKR      NaN        NaN        5.0
38             10.0  ...           RCB      NaN        9.0       81.0

     player_of_the_match            top_scorer  highscore  \
0            Jacob Duffy          Ishan Kishan       80.0
1         Shardul Thakur        Ryan Rickelton       81.0
2          Nandre Burger  Vaibhav Sooryavanshi       52.0
3        Cooper Connolly       Cooper Connolly       72.0
4           Sameer Rizvi          Sameer Rizvi       70.0
5     Nitish Kumar Reddy  Angkrish Raghuvanshi       52.0
6          Priyansh Arya           Ayush Matre       73.0
7           Sameer Rizvi          Sameer Rizvi       90.0
8           Ravi Bishnoi           Dhruv Jurel       75.0
9         Mohammed Shami          Rishabh Pant       68.0
10             Tim David             Tim David       70.0
11                   NaN                   NaN        NaN
12      Yashasvi Jaiswal      Yashasvi Jaiswal       77.0
13           Rashid Khan              KL Rahul       92.0
14       Mukul Choudhary       Mukul Choudhary       54.0
15  Vaibhav Sooryavanshi           Dhruv Jurel       81.0
16          Shreyas Iyer       Abhishek Sharma       74.0
17          Sanju Samson          Sanju Samson      115.0
18       Prasidh Krishna           Jos Buttler       60.0
19             Phil Salt             Phil Salt       78.0
20          Praful Hinge          Ishan Kishan       91.0
21            Noor Ahmad          Sanju Samson       48.0
22        Josh Hazlewood           Virat Kohli       49.0
23        Arshdeep Singh       Quinton de Kock      112.0
24          Shubman Gill          Shubman Gill       86.0
25        Tristan Stubbs             Phil Salt       63.0
26         Eshan Malinga       Abhishek Sharma       59.0
27    Varun Chakravarthy           Rinku Singh       53.0
28         Priyansh Arya         Priyansh Arya       93.0
29           Tilak Varma           Tilak Varma      101.0
30       Abhishek Sharma       Abhishek Sharma      135.0
31       Ravindra Jadeja        Mitchell Marsh       55.0
32          Sanju Samson          Sanju Samson      101.0
33           Virat Kohli         Sai Sudarshan      100.0
34              KL Rahul              KL Rahul      152.0
35          Ishan Kishan  Vaibhav Sooryavanshi      103.0
36         Kagiso Rabada         Sai Sudarshan       87.0
37           Rinku Singh           Rinku Singh       83.0
38        Josh Hazlewood      Devdutt Padikkal       34.0

           best_bowling best_bowling_figure  super_over_match
0           Jacob Duffy               3--22                No
1        Shardul Thakur               3--39                No
2          Jofra Archer               2--19                No
3       Prasidh Krishna               3--29                No
4           Lungi Ngidi               3--27                No
5   Blessing Muzarabani               4--41                No
6     Vijaykumar Vyshak               2--38                No
7          Mukesh Kumar               2--26                No
8          Ravi Bishnoi               4--41                No
9        Mohammed Shami                2--9                No
10    Bhuvneshwar Kumar               3--41                No
11                  NaN                 NaN                No
12       Sandeep Sharma               2--26                No
13          Rashid Khan               3--17                No
14           Anukul Roy               2--32                No
15        Krunal Pandya               2--30                No
16        Shivang Kumar               3--33                No
17        Jamie Overton               4--18                No
18      Prasidh Krishna               4--28                No
19        Suyash Sharma               2--47                No
20        Sakib Hussain               4--24                No
21           Noor Ahmad               3--21                No
22         Rasikh Salam               4--24                No
23       Arshdeep Singh               3--22                No
24        Kagiso Rabada               3--29                No
25    Bhuvneshwar Kumar               3--26                No
26        Eshan Malinga               3--29                No
27   Varun Chakravarthy               3--14                No
28         Prince Yadav               2--25                No
29        Ashwani Kumar               4--24                No
30        Eshan Malinga               4--32                No
31         Jofra Archer               3--20                No
32         Akeal Hosein               4--17                No
33          Rashid Khan               2--49                No
34        Kuldeep Yadav               2--46                No
35         Jofra Archer               2--34                No
36        Kagiso Rabada               3--25                No
37          Mohsin Khan               5--23               Yes
38       Josh Hazlewood               4--12                No

[39 rows x 23 columns]>

In [101]:
matches['team1'] = matches['team1'].replace(
    'Delhi Daredevils',
    'Delhi Capitals'
)

In [102]:
matches.to_csv('ipl_new.csv', index=False)